/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_fgffmpeg_FgAVUtils_FgFFmpegProgressCallback */

#ifndef _Included_com_github_fgffmpeg_FgAVUtils_FgFFmpegProgressCallback
#define _Included_com_github_fgffmpeg_FgAVUtils_FgFFmpegProgressCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
