/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_fgffmpeg_FgAVUtils */

#ifndef _Included_com_github_fgffmpeg_FgAVUtils
#define _Included_com_github_fgffmpeg_FgAVUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_fgffmpeg_FgAVUtils
 * Method:    getFileInfo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_fgffmpeg_FgJNIAVUtils_getFileInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_fgffmpeg_FgAVUtils
 * Method:    ffmpegMain
 * Signature: (J[Ljava/lang/String;Lcom/github/fgffmpeg/FgAVUtils/FgFFmpegProgressCallback;)I
 */
JNIEXPORT jint JNICALL Java_com_github_fgffmpeg_FgJNIAVUtils_ffmpegMain
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
